version: "3.6"
services:
  influxdb:
    image: arm32v7/influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    privileged: true
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - /home/devid/auto_ac/influxdb_stack/grafana.ini:/etc/grafana/grafana.ini
